#ifndef filska_instructions_all_hpp
#define filska_instructions_all_hpp

#include "filska/instruction/Acs.hpp"
#include "filska/instruction/Asn.hpp"
#include "filska/instruction/Atn.hpp"
#include "filska/instruction/Bop.hpp"
#include "filska/instruction/Cel.hpp"
#include "filska/instruction/Chr.hpp"
#include "filska/instruction/Cmp.hpp"
#include "filska/instruction/Cos.hpp"
#include "filska/instruction/Dec.hpp"
#include "filska/instruction/Exp.hpp"
#include "filska/instruction/Flr.hpp"
#include "filska/instruction/Gto.hpp"
#include "filska/instruction/Hlt.hpp"
#include "filska/instruction/Inc.hpp"
#include "filska/instruction/Ipt.hpp"
#include "filska/instruction/Jmp.hpp"
#include "filska/instruction/Jpr.hpp"
#include "filska/instruction/Log.hpp"
#include "filska/instruction/Neg.hpp"
#include "filska/instruction/Prt.hpp"
#include "filska/instruction/Rnd.hpp"
#include "filska/instruction/Set.hpp"
#include "filska/instruction/Sin.hpp"
#include "filska/instruction/Sqr.hpp"
#include "filska/instruction/Swp.hpp"
#include "filska/instruction/Tan.hpp"
#include "filska/instruction/Tmx.hpp"
#include "filska/instruction/Tmy.hpp"
#include "filska/instruction/Tmz.hpp"
#include "filska/instruction/Tst.hpp"
#include "filska/instruction/Txm.hpp"
#include "filska/instruction/Tym.hpp"
#include "filska/instruction/Tzm.hpp"

#endif
